In [ ]:
document = ["Machine learning is amazing! ",
           "deep learning is a subset of machine learning.",
           "natural language processing is a part of AI.",
           "AI is transforming the world."]
from sklearn.feature_extraction.text import CountVectorizer


In [ ]:
cv = CountVectorizer(max_df=0.95 , min_df=2 , stop_words='english')

dtm = cv.fit_transform(document)   # conveert text to document - term matrix

print(cv.get_feature_names_out())   # display remaining words
print(dtm.toarray())    #show word counts is documnet

['ai' 'learning' 'machine']
[[0 1 1]
 [0 2 1]
 [1 0 0]
 [1 0 0]]


In [ ]:
document = ["Machine learning is amazing! ",
           "deep learning is a subset of machine learning.",
           "natural language processing is a part of AI.",
           "AI is transforming the world."]

cv = CountVectorizer(stop_words='english')

dtm = cv.fit_transform(document)   # conveert text to document - term matrix\
feature_names = cv.get_feature_names_out()


import random

for i in range(1 , 10):
    random_word_id = random.randint(0 , len(feature_names)-1)
    print(feature_names[random_word_id])


deep
deep
machine
language
subset
processing
natural
ai
processing


In [ ]:
import numpy as np
from sklearn.decomposition import LatentDirichletAllocation

from sklearn.feature_extraction.text import CountVectorizer


doc = [
    "I love machine learning and Data science.",
    "Deep learning is a subset of Machine learning.",
    "I enjoy playing football and watching sports.",
    "Sports analytics is an interesting field.",

]

vectorizer = CountVectorizer(stop_words='english')
dtm = vectorizer.fit_transform(doc)

#train lda model
lda = LatentDirichletAllocation(n_components=2 , random_state= 40)
lda.fit(dtm)

#get topic distribution for each doc
topic_results = lda.transform(dtm)

#identify the dominat topic for each doc
dominant_topics = topic_results.argmax(axis=1)

#print result

for i , topic in enumerate(dominant_topics):
  print(f"doc{i+1} is mostly about topic{topic}")

doc1 is mostly about topic1
doc2 is mostly about topic1
doc3 is mostly about topic0
doc4 is mostly about topic0


train LDA  model lda.fit(dtm)

LDA learn

topic - word distrribution

Document - topic distribution

uses probabilistic inference internally

get topic distribution per docment

topic_results = lda.transform(dtm)

return probsbilty of each topic in each dosument

shape :

number of document * number of topic

examle:

[0.90 , 0.10] --> topic 0, 10% topic 1

Find domint tpic

dominat _topic = topic_resukt .argmax(axis=1)

argmax(axis =1 ) selects the topic with higest probabilty

each docmunent is assigned its most dominant topic

example :

[0,0,1,1]

print filan result

for i , topic in enumerate(dominant_topics):
  print(f"doc{i+1} is mostly about topic{topic}")

  lpops through doc

